server:
  port: 8000
  #  ?? ?? 8000 ??? ????? ?
  servlet:
    context-path: /library
    # /blog ?? ??? ??? ??? ?? ??
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?serverTimezone=Asia/Seoul
    username: root
    password: dmlcks577

  jpa:
    open-in-view: true
    hibernate:
      #ddl auto? create? ?? ????? ? ?? ???? ???? ?? ??? ? , update? ?? ??? ?? ???? ??? ??? ,none? ??
      ddl-auto: create
      naming:
        #physicalNamingStrategyStandardImpl: entity(mysql? ???)? ??? ??? ??? ?????? feed? ????
        #SpringPhysicalNamingStrategy:camel????? ??? ???? snake????? ??? ?????? feed? ??
        #??? getinthere.tistory.com/20
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #jpa? ???? ?? ??? ??? ???? ???
      use-new-id-generator-mappings: false
      #MySQL?? ??? ? ????? MySQL?? ???
    show-sql: true
    #MySQL ?? ???? ??? ? ??? ?? ????
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false